/* =========================================================
   Fotocopiadora SyP — Catálogo y Matriz de Compatibilidad
   ========================================================= */

const CATEGORIES = [
  { id: 'fotocopiadoras', label: 'Fotocopiadoras' },
  { id: 'impresoras', label: 'Impresoras' },
  { id: 'tintas', label: 'Tintas y Tóneres' },
  { id: 'repuestos', label: 'Repuestos' },
  { id: 'accesorios', label: 'Accesorios' },
  { id: 'mantenimiento', label: 'Mantenimiento' },
];

/* Series y Familias Ricoh para el Buscador de Compatibilidad */
const BRAND_MODELS = {
  'Ricoh Multifuncionales MP (B/N)': [
    'Aficio MP 301 SPF',
    'MP 2554 / 3054 / 3554',
    'MP 4002 / 5002',
    'MP 5054 / 6054 Alto Volumen',
    'MP 2501 / 2001',
    'Aficio MP 171 / 201'
  ],
  'Ricoh Color Láser (MP C / IM C)': [
    'MP C306 / C406 Color',
    'MP C2003 / C2503 Color',
    'MP C3003 / C3503 Color HD',
    'MP C4503 / C5503 Alto Rendimiento',
    'IM C2000 / C3000 Smart Series'
  ],
  'Ricoh Impresoras Láser': [
    'Ricoh SP 3710DN Láser',
    'Ricoh P 501 Alta Velocidad',
    'Ricoh SP C250SF Color'
  ],
  'Ricoh Producción & Alto Volumen': [
    'Ricoh Pro 8100EX / 8200S',
    'Ricoh Pro C5100S / C5200S Color',
    'Ricoh MP 7502 / 9002'
  ]
};

const ICONS = {
  fotocopiadoras: `<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><rect x="8" y="16" width="32" height="18" rx="1.5"/><rect x="13" y="6" width="22" height="10" rx="1"/><rect x="17" y="28" width="14" height="10" rx="0.5"/><circle cx="13" cy="21" r="1.4" fill="currentColor" stroke="none"/><line x1="18" y1="21" x2="30" y2="21"/></svg>`,
  impresoras: `<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><rect x="10" y="17" width="28" height="14" rx="1.5"/><rect x="14" y="7" width="20" height="10"/><rect x="15" y="31" width="18" height="10"/><circle cx="32" cy="23" r="1.4" fill="currentColor" stroke="none"/></svg>`,
  tintas: `<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M24 6 L32 20 A8 8 0 1 1 16 20 Z"/><line x1="19" y1="24" x2="29" y2="24"/></svg>`,
  repuestos: `<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><circle cx="24" cy="24" r="8"/><path d="M24 10v4M24 34v4M38 24h-4M14 24h-4M33.6 14.4l-2.8 2.8M17.2 30.8l-2.8 2.8M33.6 33.6l-2.8-2.8M17.2 17.2l-2.8-2.8"/></svg>`,
  accesorios: `<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><rect x="9" y="9" width="14" height="14" rx="1.5"/><rect x="25" y="9" width="14" height="14" rx="1.5"/><rect x="9" y="25" width="14" height="14" rx="1.5"/><rect x="25" y="25" width="14" height="14" rx="1.5"/></svg>`,
  mantenimiento: `<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M31 9a8 8 0 0 0-10.9 9.1L9 29.2V39h9.8l11.1-11.1A8 8 0 0 0 39 17a7.9 7.9 0 0 0-1.3-4.4L31.9 18.4 29.6 16 35.4 10.3A8 8 0 0 0 31 9Z"/></svg>`,
};

const PRODUCTS = [
  {
    id: 'sp-2554c',
    name: 'Multifuncional Láser Ricoh MP 2554',
    cat: 'fotocopiadoras',
    price: 3400000,
    spec: '35 ppm · copia, imprime y escanea · hasta 20.000 pág/mes',
    stock: 'ok',
    models: ['MP 2554 / 3054 / 3554'],
    brand: 'Ricoh',
    img: 'img/prod_copier.jpg',
    rating: 4.9,
    reviews: 42,
    badge: 'Más Vendido',
    discount: 10,
    speed: '35 ppm',
    dutyCycle: '20.000 pág/mes',
    paperSize: 'Carta, Oficio, Doble Carta (A3 / A4)',
    connectivity: 'Red Gigabit Ethernet, USB 2.0, SD Card',
    functions: 'Copia, Impresión de Red, Escáner Dúplex Color',
    tonerYield: '24.000 páginas al 5%',
    costPerPage: '$8 COP / página',
    compatibleIds: ['sp-ton2554', 'sp-cil2554', 'sp-correa'],
  },
  {
    id: 'sp-600bn',
    name: 'Multifuncional Láser B/N Ricoh MP 301 SPF',
    cat: 'fotocopiadoras',
    price: 1850000,
    spec: '31 ppm · dúplex automático · escáner a color',
    stock: 'ok',
    models: ['Aficio MP 301 SPF'],
    brand: 'Ricoh',
    img: 'img/prod_copier.jpg',
    rating: 4.8,
    reviews: 36,
    badge: 'Recomendado',
    speed: '31 ppm',
    dutyCycle: '10.000 pág/mes',
    paperSize: 'Carta, Oficio, Legal (A4)',
    connectivity: 'Red Ethernet 10/100, USB 2.0',
    functions: 'Copia, Impresión, Escáner a Color, Dúplex',
    tonerYield: '8.000 páginas',
    costPerPage: '$9 COP / página',
    compatibleIds: ['sp-ton301', 'sp-cil301', 'sp-correa'],
  },
  {
    id: 'sp-c306',
    name: 'Multifuncional Color Ricoh MP C306 HD',
    cat: 'fotocopiadoras',
    price: 2600000,
    spec: '30 ppm · pantalla táctil 10.1" · red gigabit',
    stock: 'ok',
    models: ['MP C306 / C406 Color'],
    brand: 'Ricoh',
    img: 'img/prod_copier.jpg',
    rating: 5.0,
    reviews: 19,
    badge: 'Color HD',
    speed: '30 ppm Color / B&N',
    dutyCycle: '15.000 pág/mes',
    paperSize: 'Carta, Oficio, Folio',
    connectivity: 'Pantalla Smart 10.1", Gigabit LAN, WiFi opcional',
    functions: 'Multifuncional Color Láser, Escáner de Alta Definición',
    tonerYield: '17.000 pág (Negro) / 12.000 (Color)',
    costPerPage: '$35 COP / pág color',
    compatibleIds: ['sp-ton4501c', 'sp-banda'],
  },
  {
    id: 'sp-5054',
    name: 'Multifuncional Láser Ricoh MP 5054 Industrial',
    cat: 'fotocopiadoras',
    price: 4900000,
    spec: '50 ppm B/N · alto volumen industrial · hasta 50.000 pág/mes',
    stock: 'ok',
    models: ['MP 5054 / 6054 Alto Volumen'],
    brand: 'Ricoh',
    img: 'img/prod_copier.jpg',
    rating: 4.9,
    reviews: 58,
    badge: 'Alto Volumen',
    discount: 5,
    speed: '50 ppm',
    dutyCycle: '50.000 pág/mes',
    paperSize: 'Carta, Oficio, Doble Carta (A3/A4)',
    connectivity: 'Red Gigabit, USB Host 2.0, Disco Duro 320GB',
    functions: 'Copia, Impresión de Red, Escaneo Dúplex simultáneo 180 ipm',
    tonerYield: '37.000 páginas',
    costPerPage: '$6 COP / página',
    compatibleIds: ['sp-ton5054', 'sp-cil2554', 'sp-correa'],
  },
  {
    id: 'sp-p501',
    name: 'Impresora Láser Monocromática Ricoh P 501',
    cat: 'impresoras',
    price: 1350000,
    spec: '45 ppm · dúplex automático · red gigabit y bajo consumo',
    stock: 'ok',
    models: ['Ricoh P 501 Alta Velocidad'],
    brand: 'Ricoh',
    img: 'img/prod_printer.jpg',
    rating: 4.8,
    reviews: 24,
    badge: 'Alto Rendimiento',
    speed: '45 ppm',
    dutyCycle: '80.000 pág/mes',
    paperSize: 'Carta, Oficio, Ejecutivo',
    connectivity: 'Red Gigabit Ethernet, USB 2.0',
    functions: 'Impresora Láser Monocromática de Alta Velocidad',
    tonerYield: '14.000 páginas',
    costPerPage: '$8 COP / página',
    compatibleIds: ['sp-recarga1000'],
  },
  {
    id: 'sp-p220c',
    name: 'Impresora Color Ricoh SP C250SF',
    cat: 'impresoras',
    price: 1450000,
    spec: '22 ppm color · WiFi y Ethernet integrados',
    stock: 'ok',
    models: ['MP C2003 / C2503 Color'],
    brand: 'Ricoh',
    img: 'img/prod_printer.jpg',
    rating: 4.8,
    reviews: 15,
    badge: 'WiFi Direct',
    speed: '22 ppm Color / B&N',
    dutyCycle: '30.000 pág/mes',
    paperSize: 'Carta, Oficio, A4',
    connectivity: 'WiFi Direct, Ethernet, USB 2.0',
    functions: 'Impresión Láser Color inalámbrica',
    tonerYield: '6.000 páginas',
    costPerPage: '$38 COP / página',
    compatibleIds: ['sp-ton4501c'],
  },
  {
    id: 'sp-ton301',
    name: 'Tóner Ricoh MP 301 (Tipo 301 / 1270D)',
    cat: 'tintas',
    price: 34000,
    spec: 'Rendimiento aprox. 8.000 páginas al 5%',
    stock: 'ok',
    models: ['Aficio MP 301 SPF'],
    brand: 'Ricoh',
    img: 'img/prod_toner.jpg',
    rating: 4.9,
    reviews: 95,
    badge: 'Top Ventas',
  },
  {
    id: 'sp-ton2554',
    name: 'Tóner Negro Ricoh MP 2554 / 3054 / 3554',
    cat: 'tintas',
    price: 78000,
    spec: 'Rendimiento aprox. 24.000 páginas',
    stock: 'ok',
    models: ['MP 2554 / 3054 / 3554'],
    brand: 'Ricoh',
    img: 'img/prod_toner.jpg',
    rating: 5.0,
    reviews: 73,
    badge: 'Original / Homologado',
  },
  {
    id: 'sp-ton5054',
    name: 'Tóner Negro Ricoh MP 5054 / 6054',
    cat: 'tintas',
    price: 92000,
    spec: 'Rendimiento aprox. 37.000 páginas al 5%',
    stock: 'ok',
    models: ['MP 5054 / 6054 Alto Volumen'],
    brand: 'Ricoh',
    img: 'img/prod_toner.jpg',
    rating: 4.9,
    reviews: 48,
    badge: 'Larga Duración',
  },
  {
    id: 'sp-ton4501c',
    name: 'Kit Tóner Color Ricoh MP C306 / C406 (CMYK)',
    cat: 'tintas',
    price: 216000,
    spec: '17.000 pág. negro / 12.000 pág. colores',
    stock: 'ok',
    models: ['MP C306 / C406 Color'],
    brand: 'Ricoh',
    img: 'img/hero_toner.jpg',
    rating: 4.9,
    reviews: 29,
    badge: 'Kit x4',
    discount: 8,
  },
  {
    id: 'sp-recarga1000',
    name: 'Polvo de Tóner Ricoh Micro-filtrado 1000gr',
    cat: 'tintas',
    price: 95000,
    spec: 'Micro-filtrado de alta densidad · negro profundo para toda la serie MP',
    stock: 'ok',
    models: ['Aficio MP 301 SPF', 'MP 2554 / 3054 / 3554', 'MP 5054 / 6054 Alto Volumen'],
    brand: 'Ricoh',
    img: 'img/prod_toner.jpg',
    rating: 4.9,
    reviews: 64,
  },
  {
    id: 'sp-cil2554',
    name: 'Cilindro Tambor OPC Ricoh MP 2554 / 3554 / 5054',
    cat: 'repuestos',
    price: 61000,
    spec: 'Duración certificada 60.000 páginas',
    stock: 'ok',
    models: ['MP 2554 / 3054 / 3554', 'MP 5054 / 6054 Alto Volumen'],
    brand: 'Ricoh',
    img: 'img/prod_supplies.jpg',
    rating: 4.9,
    reviews: 38,
    badge: 'Alta Duración',
  },
  {
    id: 'sp-cil301',
    name: 'Cilindro OPC + Cuchilla Ricoh MP 301',
    cat: 'repuestos',
    price: 48000,
    spec: 'Kit completo de revelado y limpieza',
    stock: 'ok',
    models: ['Aficio MP 301 SPF'],
    brand: 'Ricoh',
    img: 'img/prod_supplies.jpg',
    rating: 4.8,
    reviews: 27,
  },
  {
    id: 'sp-banda',
    name: 'Banda de Transferencia Ricoh MP C2503 / C306',
    cat: 'repuestos',
    price: 280000,
    spec: 'Vida útil 120.000–150.000 copias',
    stock: 'ok',
    models: ['MP C306 / C406 Color', 'MP C2003 / C2503 Color'],
    brand: 'Ricoh',
    img: 'img/prod_supplies.jpg',
    rating: 5.0,
    reviews: 14,
  },
  {
    id: 'sp-correa',
    name: 'Gomas de Alimentación de Papel Ricoh (Pick Up Rollers)',
    cat: 'repuestos',
    price: 28000,
    spec: 'Set x3 unidades antideslizantes originales Ricoh',
    stock: 'ok',
    models: ['Aficio MP 301 SPF', 'MP 2554 / 3054 / 3554', 'MP 5054 / 6054 Alto Volumen'],
    brand: 'Ricoh',
    img: 'img/prod_supplies.jpg',
    rating: 4.7,
    reviews: 41,
  },
  {
    id: 'sp-kitstd',
    name: 'Mantenimiento Preventivo Completo Ricoh en Taller',
    cat: 'mantenimiento',
    price: 120000,
    spec: 'Desarme, soplado, lubricación y calibración óptica para equipos Ricoh',
    stock: 'ok',
    models: ['Aficio MP 301 SPF', 'MP 2554 / 3054 / 3554', 'MP 5054 / 6054 Alto Volumen'],
    brand: 'Ricoh',
    img: 'img/service_workshop.jpg',
    rating: 5.0,
    reviews: 83,
    badge: 'Garantizado',
  },
  {
    id: 'sp-visita',
    name: 'Visita Técnica de Emergencia / Diagnóstico Ricoh',
    cat: 'mantenimiento',
    price: 45000,
    spec: 'Atención prioritaria en sitio para equipos Ricoh · Neiva y perímetro',
    stock: 'ok',
    models: ['Aficio MP 301 SPF', 'MP 2554 / 3054 / 3554', 'MP 5054 / 6054 Alto Volumen'],
    brand: 'Ricoh',
    img: 'img/hero_service.jpg',
    rating: 4.9,
    reviews: 97,
    badge: 'Express &lt; 24h',
  },
];

/* ============================================================
   MATRIZ DE DIAGNÓSTICO DE FALLAS (Smart Troubleshooter)
   ============================================================ */
const TROUBLESHOOTING_DATA = [
  {
    id: 'falla-rayas',
    symptom: 'Líneas negras verticales o rayas repetitivas',
    category: 'Calidad de Copia Ricoh',
    severity: 'Media',
    desc: 'La hoja sale con una o varias líneas negras continuas que manchan el documento a lo largo de la página.',
    diagnosis: 'Cilindro Tambor OPC Ricoh rayado o cuchilla de limpieza (Cleaning Blade) con desgaste por residuos de polvo.',
    solution: 'Reemplazo del Cilindro OPC Ricoh y Cuchilla de limpieza, más aspirado técnico de la tolva residual.',
    productId: 'sp-cil2554',
    serviceId: 'sp-kitstd',
    urgency: 'Atención en 24h para evitar contaminar la unidad reveladora',
  },
  {
    id: 'falla-atasco',
    symptom: 'Atasco continuo de papel en Bandeja 1 o Alimentador ARDF',
    category: 'Mecánica de Alimentación Ricoh',
    severity: 'Alta',
    desc: 'La máquina intenta tomar la hoja pero patina, se arruga en la entrada o reporta error "Atasco de Papel" de inmediato.',
    diagnosis: 'Gomas de arrastre Ricoh (Pick-up Rollers) cristalizadas, lisas o con suciedad acumulada de papel bond.',
    solution: 'Cambio de set de gomas de alimentación Ricoh (3 rodillos antideslizantes) y calibración de resorte de presión.',
    productId: 'sp-correa',
    serviceId: 'sp-visita',
    urgency: 'Solución rápida en sitio (< 30 min)',
  },
  {
    id: 'falla-codigo',
    symptom: 'Código de error SC en pantalla Ricoh (ej. SC 542 / SC 320 / SC 401)',
    category: 'Electrónica y Fusor Ricoh',
    severity: 'Crítica',
    desc: 'La fotocopiadora Ricoh se bloquea con una pantalla de código de servicio que impide realizar copias o impresiones.',
    diagnosis: 'Falla térmica en termistor/fusor o desincronización de motor poligonal láser Ricoh. Bloqueo de seguridad preventivo.',
    solution: 'Diagnóstico con multímetro y modo de servicio SP Ricoh en taller o domicilio, reseteo SP y recambio de pieza.',
    productId: null,
    serviceId: 'sp-visita',
    urgency: 'Prioridad de emergencia inmediata',
  },
  {
    id: 'falla-palido',
    symptom: 'Impresión muy clara, pálida o fondo grisáceo sucio',
    category: 'Densidad y Tóner Ricoh',
    severity: 'Baja',
    desc: 'El texto no sale negro profundo o el fondo de la hoja queda con sombra de polvo residual.',
    diagnosis: 'Polvo de tóner descalibrado, rodillo magnético sucio o sensor ID de densidad óptico Ricoh obstruido.',
    solution: 'Recarga con tóner Ricoh microfiltrado Grado A+ y calibración óptica de sensor TD/ID en modo SP.',
    productId: 'sp-ton2554',
    serviceId: 'sp-kitstd',
    urgency: 'Mantenimiento preventivo recomendado',
  },
  {
    id: 'falla-ruido',
    symptom: 'Ruido fuerte de carraca / chasquido de engranajes Ricoh',
    category: 'Tracción Mecánica Ricoh',
    severity: 'Media',
    desc: 'Al presionar botón de copia se escucha un sonido metálico o chasquido de piñones forzados.',
    diagnosis: 'Engranaje de fusión Ricoh roto o buje de registro trabado por falta de lubricación de alta temperatura.',
    solution: 'Desarme de módulo de tracción Ricoh, lubricación sintética y sustitución de piñón desgastado.',
    productId: null,
    serviceId: 'sp-kitstd',
    urgency: 'Requiere revisión para no romper el motor principal',
  },
];

/* ============================================================
   DICCIONARIO DE CÓDIGOS DE ERROR SC RICOH (SC Code Lookup)
   ============================================================ */
const RICOH_SC_CODES = [
  {
    code: 'SC 541',
    name: 'Termistor Central de Fusión Abierto / Desconectado',
    category: 'Unidad de Fusión',
    severity: 'Crítica',
    meaning: 'El termistor principal de la unidad fusora detecta circuito abierto o no registra temperatura en el encendido.',
    cause: 'Termistor sucio con costra de tóner, cable roto en el arnés de la unidad fusora o conector desajustado.',
    solution: 'Revisión y reemplazo de termistores centrales, limpieza de bornes de contacto y reseteo en Modo de Servicio SP (SP 5-810).',
    partSuggested: 'Termistor de Fusión Ricoh MP 2554 / 301',
    safetyNotice: '⚠️ No fuerce el encendido repetido. Requiere reseteo técnico en código de servicio SP.',
  },
  {
    code: 'SC 542',
    name: 'Falla de Calentamiento en Fusor (Warm-up Error)',
    category: 'Unidad de Fusión',
    severity: 'Crítica',
    meaning: 'El rodillo de calor no alcanza la temperatura de fusión en el tiempo programado tras el encendido.',
    cause: 'Termistor de fusión sucio/abierto, lámpara halógena de calor quemada o termostato de seguridad disparado por variación de voltaje.',
    solution: 'Revisión y cambio de termistores, medición de continuidad en lámparas calefactoras y reseteo en Modo de Servicio SP (SP 5-810).',
    partSuggested: 'Termistor / Rodillo de Calor Ricoh MP 2554 / 301',
    safetyNotice: '⚠️ No apague y encienda repetidamente la máquina. Requiere reset técnico de seguridad.',
  },
  {
    code: 'SC 543',
    name: 'Sobrecalentamiento en Unidad de Fusión',
    category: 'Unidad de Fusión',
    severity: 'Crítica',
    meaning: 'El sensor de temperatura detecta calor por encima del límite de seguridad (> 230°C).',
    cause: 'Triac de la tarjeta de alimentación en corto, termistor descalibrado o falla en el circuito de control térmico.',
    solution: 'Apagar de inmediato el equipo, verificar tarjeta de fuente y cambiar termostato/termistor antes de reiniciar.',
    partSuggested: 'Termostato de Seguridad / Termistor Ricoh',
    safetyNotice: 'Riesgo térmico: Desconecte el equipo de la toma eléctrica de inmediato.',
  },
  {
    code: 'SC 320',
    name: 'Error de Motor Poligonal Láser',
    category: 'Óptica y Láser',
    severity: 'Alta',
    meaning: 'El motor del espejo poligonal de la unidad óptica láser no alcanza la velocidad de rotación especificada.',
    cause: 'Acumulación de polvo de tóner en el eje del motor poligonal, arnés de cables desconectado o tarjeta controladora de láser defectuosa.',
    solution: 'Desarme y limpieza técnica del bloque óptico láser, lubricación de eje cerámico o sustitución del motor poligonal.',
    partSuggested: 'Motor Poligonal Láser Ricoh Serie MP',
    safetyNotice: 'Requiere manipulación en banco libre de estática y polvo en taller.',
  },
  {
    code: 'SC 401',
    name: 'Fuga de Alta Tensión en Rodillo de Transferencia',
    category: 'Transferencia e Imagen',
    severity: 'Alta',
    meaning: 'Se detecta fuga de corriente o corto en la polarización del rodillo de transferencia de imagen.',
    cause: 'Rodillo de transferencia con acumulación de humedad/polvo residual, terminales oxidados o paquete de alta tensión averiado.',
    solution: 'Limpieza y secado de contactos de alta tensión, recambio de rodillo de transferencia y calibración de polarización SP.',
    partSuggested: 'Rodillo de Transferencia Ricoh MP 301 / 2554',
    safetyNotice: 'Verificar humedad relativa del papel en la bandeja.',
  },
  {
    code: 'SC 440',
    name: 'Falla en Motor de Banda de Transferencia ITB',
    category: 'Transferencia de Color',
    severity: 'Alta',
    meaning: 'El sensor de rotación de la banda intermedia de transferencia (ITB) no detecta giro continuo.',
    cause: 'Banda de transferencia trabada por residuo de tóner, cuchilla de banda atorada o motor de arrastre quemado.',
    solution: 'Inspección de banda ITB, reemplazo de cuchilla de limpieza de banda y engrase de rodamientos.',
    partSuggested: 'Banda de Transferencia Ricoh MP C2503 / C306',
    safetyNotice: 'Manejar la banda por los extremos sin tocar la película fotosensible.',
  },
  {
    code: 'SC 670',
    name: 'Error de Arranque de la Tarjeta Principal (Engine Start-up)',
    category: 'Electrónica / Engine',
    severity: 'Crítica',
    meaning: 'La placa de control del motor (BCU/Engine Board) no responde a la señal de encendido de la controladora.',
    cause: 'Caída de voltaje en la red eléctrica, conector de bus PCI flojo o memoria NVRAM desprogramada.',
    solution: 'Verificar fuente de poder con multímetro, limpiar pistas de la tarjeta BCU y reconectar arnés principal.',
    partSuggested: 'Diagnóstico Electrónico de Planta SyP',
    safetyNotice: 'Desconecte de la red y verifique polo a tierra antes de encender.',
  },
  {
    code: 'SC 672',
    name: 'Error de Comunicación Controladora - Panel Táctil',
    category: 'Electrónica / BIOS',
    severity: 'Crítica',
    meaning: 'La tarjeta controladora principal (Motherboard) no recibe respuesta del panel de control tras el encendido.',
    cause: 'Módulo de memoria RAM o disco duro trabado, cable plano del panel flojo o firmware desactualizado.',
    solution: 'Reseteo en frío, limpieza de contactos de memoria RAM con alcohol isopropílico y verificación de voltajes de la fuente.',
    partSuggested: 'Diagnóstico Electrónico de Planta SyP',
    safetyNotice: 'Desconecte de la toma eléctrica antes de cualquier inspección.',
  },
  {
    code: 'SC 501',
    name: 'Falla del Motor Elevador de Bandeja 1',
    category: 'Alimentación de Papel',
    severity: 'Media',
    meaning: 'El sensor de límite superior de la bandeja de papel 1 no se activa cuando el motor eleva el papel.',
    cause: 'Mecanismo de elevación atascado por clips/grapas, sensor de altura desconectado o piñón elevador roto.',
    solution: 'Retiro de objetos extraños en fondo de bandeja, lubricación de cremallera y calibración de sensor de elevación.',
    partSuggested: 'Sensor de Altura / Motor Elevador Ricoh',
    safetyNotice: 'Retire la resma de papel y verifique el fondo de la bandeja.',
  },
  {
    code: 'SC 502',
    name: 'Falla del Motor Elevador de Bandeja 2',
    category: 'Alimentación de Papel',
    severity: 'Media',
    meaning: 'La bandeja de papel inferior no eleva la resma hacia las gomas de alimentación.',
    cause: 'Sobrecarga de papel, resorte de elevación destensado o motor paso a paso de bandeja 2 con engranaje desgastado.',
    solution: 'Revisión del juego de piñones de tracción de bandeja 2 y lubricación con grasa técnica.',
    partSuggested: 'Juego de Piñones Elevadores Ricoh',
    safetyNotice: 'No sobrepasar la línea MAX indicada en el lateral de la bandeja.',
  },
  {
    code: 'SC 899',
    name: 'Desbordamiento de Buffer de Spooler / Print Server',
    category: 'Software / Red',
    severity: 'Baja',
    meaning: 'La controladora de impresión se bloqueó al recibir un archivo PDF o documento web corrupto por la red.',
    cause: 'Trabajo de impresión malicioso o incompatible con el driver PCL/PostScript enviado desde un computador de la red.',
    solution: 'Desconectar cable de red, cancelar cola de impresión en los computadores y reiniciar fotocopiadora con memoria liberada.',
    partSuggested: 'Actualización de Driver Ricoh PCL6',
    safetyNotice: 'Desconecte el cable de red LAN antes de reiniciar el equipo.',
  },
  {
    code: 'SC 302',
    name: 'Fuga de Corriente en Rodillo de Carga (Charge Roller)',
    category: 'Carga y Revelado',
    severity: 'Alta',
    meaning: 'Fuga eléctrica en el rodillo de carga de la unidad de tambor cilindro.',
    cause: 'Rodillo de carga con perforación superficial por suciedad o desgaste del cilindro OPC.',
    solution: 'Sustitución de rodillo de carga y cilindro OPC con aspirado de residuos.',
    partSuggested: 'Cilindro OPC + Rodillo de Carga Ricoh',
    safetyNotice: 'Evite tocar la superficie del cilindro con las manos desnudas.',
  },
  {
    code: 'SC 552',
    name: 'Error de Temperatura en Rodillo de Presión',
    category: 'Unidad de Fusión',
    severity: 'Crítica',
    meaning: 'La temperatura del rodillo de presión no se estabiliza durante la operación continua.',
    cause: 'Termistor de presión desgastado o acumulación de tóner quemado en la superficie sensora.',
    solution: 'Limpieza de residuos en sensor térmico o reemplazo de termistor secundario con reset de código.',
    partSuggested: 'Termistor Secundario Ricoh',
    safetyNotice: 'La unidad fusora alcanza más de 180°C. Deje enfriar antes de manipular.',
  },
  {
    code: 'SC 101',
    name: 'Error de Lámpara de Exposición del Escáner (Scanner Lamp)',
    category: 'Óptica y Escáner',
    severity: 'Media',
    meaning: 'El sensor de nivel de blanco no detecta la intensidad requerida de la lámpara de lectura al escanear.',
    cause: 'Tira de calibración blanca sucia bajo el cristal, cable plano del carro de escáner cortado o lámpara LED agotada.',
    solution: 'Limpieza minuciosa del espejo 1, 2 y tira blanca de referencia con microfibra, o recambio de barra LED.',
    partSuggested: 'Barra LED / Cable Plano de Escáner Ricoh',
    safetyNotice: 'No use solventes corrosivos en los espejos de lectura óptica.',
  },
  {
    code: 'SC 220',
    name: 'Falla de Detección de Sincronismo Láser (Laser Sync Error)',
    category: 'Óptica y Láser',
    severity: 'Alta',
    meaning: 'La tarjeta detectora de inicio de línea láser no recibe el haz de luz sincronizado.',
    cause: 'Obturador de láser cerrado mecánicamente, sensor de sincronía sucio con polvo o diodo láser desalineado.',
    solution: 'Limpieza de ventana de protección del láser y verificación del detector de sincronización.',
    partSuggested: 'Sensor Detector de Sincronismo Ricoh',
    safetyNotice: 'Protección ocular: Nunca mire directamente al diodo láser con el equipo energizado.',
  },
  {
    code: 'SC 569',
    name: 'Error de Motor de Despegue / Liberación de Presión de Fusión',
    category: 'Unidad de Fusión',
    severity: 'Media',
    meaning: 'El mecanismo que libera la presión de la fusión para sobres o papel grueso no vuelve a su posición de inicio.',
    cause: 'Sensor de posición de leva de presión atascado o piñón excéntrico roto.',
    solution: 'Limpieza del sensor de paso de leva de presión y lubricación de engranajes fusores.',
    partSuggested: 'Sensor de Leva de Presión Ricoh',
    safetyNotice: 'Permita que la fusora se enfríe durante 20 minutos antes de desmontar.',
  },
  {
    code: 'SC 860',
    name: 'Error de Inicio de Disco Duro (HDD Startup Error)',
    category: 'Almacenamiento / Sistema',
    severity: 'Media',
    meaning: 'La máquina no puede montar el disco duro interno donde se almacenan fuentes, escaneos y buzones.',
    cause: 'Sectores defectuosos en el disco duro magnético por apagados forzados o cable SATA flojo.',
    solution: 'Formateo de HDD en Modo SP (SP 5-832) o reemplazo por unidad de estado sólido / disco nuevo con recarga de firmware.',
    partSuggested: 'Disco Duro Homologado Ricoh 320GB',
    safetyNotice: 'Siempre apague la máquina desde el botón frontal antes de cortar la energía principal.',
  },
  {
    code: 'SC 990',
    name: 'Error Inesperado de Software / Rendimiento del Motor',
    category: 'Sistema y Firmware',
    severity: 'Baja',
    meaning: 'El firmware del sistema encontró una instrucción no contemplada al procesar un comando de copiado.',
    cause: 'Memoria temporal saturada, combinación incompatible de acabador/bandeja o firmware antiguo.',
    solution: 'Reinicio general del equipo y actualización del firmware oficial Ricoh a la última versión estable.',
    partSuggested: 'Actualización de Firmware Ricoh en Taller',
    safetyNotice: 'Si el error es continuo, anote las condiciones en que se genera para el técnico.',
  },
];

/* ============================================================
   PRUEBA SOCIAL Y CASOS DE ÉXITO EN EL HUILA
   ============================================================ */
const TESTIMONIALS_DATA = [
  {
    id: 'test-1',
    author: 'Dra. Carmen Cecilia Andrade',
    role: 'Administradora · Notaría Segunda de Neiva',
    entity: 'Notaría Segunda de Neiva',
    quote: 'Llevamos más de 4 años con el servicio de renting de fotocopiadoras Ricoh MP con Fotocopiadora SyP. El soporte técnico cuando se requiere es inmediato y el suministro de tóner nunca falta.',
    rating: 5,
    city: 'Neiva, Huila',
    metric: '+45.000 copias notariales/mes sin interrupciones',
  },
  {
    id: 'test-2',
    author: 'Lic. Miller González',
    role: 'Coordinador Académico',
    entity: 'Colegio Cooperativo Campestre',
    quote: 'Para la época de exámenes y talleres escolares el volumen de copiado es altísimo. Gladys y Sebastián nos asesoraron con una fotocopiadora Ricoh MP de alto rendimiento que redujo nuestros costos en más del 40%.',
    rating: 5,
    city: 'Neiva, Huila',
    metric: '40% de ahorro frente a compra tradicional',
  },
  {
    id: 'test-3',
    author: 'Ing. Fernando Perdomo',
    role: 'Director de Obra',
    entity: 'Constructora & Proyectos del Huila',
    quote: 'Imprimimos planos, memorias de cálculo y contratos a diario en nuestras impresoras Ricoh. La calidad de los insumos y el tóner es indistinguible del original, con garantía total.',
    rating: 5,
    city: 'Neiva, Huila',
    metric: '100% de nitidez en planos y contratos',
  },
  {
    id: 'test-4',
    author: 'Sandra Milena Rojas',
    role: 'Propietaria',
    entity: 'Papelería & Centro de Copiado La Toma',
    quote: 'Excelente respaldo técnico para nuestras máquinas Ricoh en la Av. La Toma. Si una máquina falla, el técnico llega el mismo día. La confianza y el trato familiar son incomparables.',
    rating: 5,
    city: 'Neiva, Huila',
    metric: 'Respuesta técnica en menos de 3 horas',
  },
];

/* ============================================================
   PARÁMETROS PARA LA CALCULADORA DE RENTING
   ============================================================ */
const RENTING_TIERS = {
  mono: [
    { maxVol: 4000, modelId: 'sp-600bn', name: 'Plan Básico Pyme (Ricoh MP 301)', monthlyFee: 190000, includedPages: 3000, extraPagePrice: 28, buyMonthlyEstimate: 290000 },
    { maxVol: 12000, modelId: 'sp-2554c', name: 'Plan Corporativo Pro (Ricoh MP 2554)', monthlyFee: 320000, includedPages: 8000, extraPagePrice: 22, buyMonthlyEstimate: 510000 },
    { maxVol: 50000, modelId: 'sp-5054', name: 'Plan Alto Volumen Industrial (Ricoh MP 5054 50ppm)', monthlyFee: 490000, includedPages: 18000, extraPagePrice: 16, buyMonthlyEstimate: 820000 },
  ],
  color: [
    { maxVol: 6000, modelId: 'sp-c306', name: 'Plan Color Studio (Ricoh C306 HD)', monthlyFee: 380000, includedPages: 2500, extraPagePrice: 75, buyMonthlyEstimate: 620000 },
    { maxVol: 50000, modelId: 'sp-c306', name: 'Plan Color Corporativo Pro (Ricoh C2503)', monthlyFee: 560000, includedPages: 6000, extraPagePrice: 65, buyMonthlyEstimate: 940000 },
  ]
};

function getCategoryDefaultImage(cat) {
  switch (cat) {
    case 'fotocopiadoras': return 'img/prod_copier.jpg';
    case 'impresoras': return 'img/prod_printer.jpg';
    case 'tintas': return 'img/prod_toner.jpg';
    case 'repuestos': return 'img/prod_supplies.jpg';
    case 'mantenimiento': return 'img/hero_service.jpg';
    default: return 'img/prod_copier.jpg';
  }
}

function formatCOP(value) {
  return '$' + Number(value).toLocaleString('es-CO');
}

/* ============================================================
   SINCRONIZACIÓN CON BACKEND REST API (FastAPI / SQLite)
   ============================================================ */
const API_BASE_URL = 'http://127.0.0.1:8000/api/v1';

async function syncProductsFromBackend() {
  try {
    const res = await fetch(`${API_BASE_URL}/products`);
    if (res.ok) {
      const data = await res.json();
      if (Array.isArray(data) && data.length > 0) {
        PRODUCTS.length = 0;
        data.forEach((item) => {
          PRODUCTS.push({
            id: item.id || item.id_code,
            name: item.name,
            cat: item.category_slug,
            price: Number(item.price),
            spec: item.spec,
            stock: item.stock_status || 'ok',
            brand: item.brand || 'Ricoh',
            models: item.compatible_models ? item.compatible_models.split(',').map((m) => m.trim()) : [],
            discount: item.discount_percent || 0,
            img: item.image_url || getCategoryDefaultImage(item.category_slug),
            rating: item.rating || 4.9,
            reviews: item.reviews_count || 25,
            badge: item.badge || '',
            speed: item.speed || '35 ppm',
            dutyCycle: item.duty_cycle || '20.000 pág/mes',
            paperSize: item.paper_size || 'Carta, Oficio, A4',
            connectivity: item.connectivity || 'Red Gigabit, USB 2.0',
            functions: item.functions || 'Copia, Impresión, Escáner',
            tonerYield: item.toner_yield || '15.000 páginas',
            costPerPage: item.cost_per_page || '$10 COP',
            compatibleIds: item.compatible_ids ? item.compatible_ids.split(',').map(s => s.trim()) : [],
          });
        });
        console.log('[SyP] ⚡ Conectado con Backend API SyP: ' + PRODUCTS.length + ' productos sincronizados.');
        if (typeof applyFilters === 'function') {
          applyFilters(false);
        }
      }
    }
  } catch (e) {
    // Si el backend está apagado, continúa con el catálogo local integrado
  }
}

// Intentar sincronización al cargar
if (typeof window !== 'undefined') {
  syncProductsFromBackend();
}

