# Generated by Django 6.1.2 on 2026-10-07 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Marca')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Categoría')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon_svg', models.TextField(blank=True, verbose_name='SVG del Icono')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('phone', models.CharField(max_length=25, verbose_name='Teléfono')),
                ('subject', models.CharField(max_length=150, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('is_read', models.BooleanField(default=False, verbose_name='¿Leído?')),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150, verbose_name='Nombre del Cliente')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('client_phone', models.CharField(max_length=25, verbose_name='Teléfono / WhatsApp')),
                ('equipment', models.CharField(max_length=150, verbose_name='Marca y Modelo del Equipo')),
                ('service_type', models.CharField(choices=[('Mantenimiento preventivo', 'Mantenimiento preventivo'), ('Mantenimiento correctivo', 'Mantenimiento correctivo'), ('Diagnóstico', 'Diagnóstico'), ('Instalación de equipo', 'Instalación de equipo'), ('Recarga / Insumos', 'Recarga / Insumos')], default='Diagnóstico', max_length=50, verbose_name='Tipo de Servicio')),
                ('scheduled_date', models.DateField(verbose_name='Fecha Deseada')),
                ('scheduled_time', models.TimeField(verbose_name='Hora Deseada')),
                ('description', models.TextField(verbose_name='Descripción de la Falla o Necesidad')),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('En proceso', 'En proceso'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20, verbose_name='Estado de la Solicitud')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas Internas de Administración')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Solicitud de Servicio Técnico',
                'verbose_name_plural': 'Solicitudes de Servicio Técnico',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(max_length=50, unique=True, verbose_name='Código de Producto / ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Precio (COP)')),
                ('spec', models.CharField(max_length=300, verbose_name='Especificaciones / Descripción corta')),
                ('stock_status', models.CharField(choices=[('ok', 'Disponible'), ('low', 'Pocas unidades'), ('out', 'Agotado')], default='ok', max_length=10, verbose_name='Disponibilidad')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='Descuento (%)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='¿Producto Destacado en Inicio?')),
                ('compatible_models', models.TextField(blank=True, help_text='Modelos compatibles separados por comas. Ej: Aficio MP 301, MP 2554', verbose_name='Modelos Compatibles')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Foto del Producto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.brand', verbose_name='Marca')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto / Insumo',
                'verbose_name_plural': 'Productos e Insumos',
                'ordering': ['-is_featured', 'name'],
            },
        ),
    ]
